default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: travel_agent_development

production:
  <<: *default
  database: travel_agent_production
  username: travel_agent
  password: <%= ENV['TRAVEL_AGENT_DATABASE_PASSWORD'] %>
