# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60ee42a6565467098b89a28063bc7cca47ad7683a4a16189a8790817e2680f85faa400351b85871389947bb20cd70b38702978a32cdae90379cdb31b3fb018e3

test:
  secret_key_base: 58e8d4ab750b3db3abb7642086265b38c07f79f85aa87f8be1bc9610c93168f34c42dab48b6bf6b241c672936a9fc60b63b15e9fd1ae94c915bea1503de0d35a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
